"""initial_schema

Revision ID: 0f8a963cea9b
Revises: 
Create Date: 2026-05-25 13:13:15.324190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa




# revision identifiers, used by Alembic.
revision: str = '0f8a963cea9b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brainstorms', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_brainstorms_created_at'), 'brainstorms', ['created_at'], unique=False)
    op.create_index(op.f('ix_brainstorms_deleted_at'), 'brainstorms', ['deleted_at'], unique=False)
    op.create_index('ix_brainstorms_deleted_at_created', 'brainstorms', ['deleted_at', 'created_at'], unique=False)
    op.create_index(op.f('ix_brainstorms_title'), 'brainstorms', ['title'], unique=False)
    op.create_index('ix_library_brainstorm_folder', 'library_entries', ['brainstorm_id', 'folder_name'], unique=False)
    op.create_index(op.f('ix_library_entries_brainstorm_id'), 'library_entries', ['brainstorm_id'], unique=False)
    op.create_index(op.f('ix_library_entries_created_at'), 'library_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_library_entries_folder_name'), 'library_entries', ['folder_name'], unique=False)
    op.create_index(op.f('ix_library_entries_topic_id'), 'library_entries', ['topic_id'], unique=False)
    op.create_index(op.f('ix_map_suggestion_dismissals_brainstorm_id'), 'map_suggestion_dismissals', ['brainstorm_id'], unique=False)
    op.create_index(op.f('ix_map_suggestion_dismissals_created_at'), 'map_suggestion_dismissals', ['created_at'], unique=False)
    op.create_index(op.f('ix_map_suggestion_dismissals_source_topic_id'), 'map_suggestion_dismissals', ['source_topic_id'], unique=False)
    op.create_index(op.f('ix_map_suggestion_dismissals_suggestion_name'), 'map_suggestion_dismissals', ['suggestion_name'], unique=False)
    op.create_index('ix_suggestion_dismissals_brainstorm', 'map_suggestion_dismissals', ['brainstorm_id', 'created_at'], unique=False)
    op.add_column('messages', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.execute("ALTER TABLE messages ALTER COLUMN metadata_json TYPE JSON USING metadata_json::json")
    op.create_index('ix_messages_brainstorm_created', 'messages', ['brainstorm_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_brainstorm_id'), 'messages', ['brainstorm_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_role'), 'messages', ['role'], unique=False)
    op.add_column('topic_edges', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_topic_edges_brainstorm_id'), 'topic_edges', ['brainstorm_id'], unique=False)
    op.create_index('ix_topic_edges_brainstorm_rel', 'topic_edges', ['brainstorm_id', 'relationship'], unique=False)
    op.create_index(op.f('ix_topic_edges_created_at'), 'topic_edges', ['created_at'], unique=False)
    op.create_index(op.f('ix_topic_edges_relationship'), 'topic_edges', ['relationship'], unique=False)
    op.create_index('ix_topic_edges_source_target', 'topic_edges', ['source_topic_id', 'target_topic_id'], unique=False)
    op.create_index(op.f('ix_topic_edges_source_topic_id'), 'topic_edges', ['source_topic_id'], unique=False)
    op.create_index(op.f('ix_topic_edges_target_topic_id'), 'topic_edges', ['target_topic_id'], unique=False)
    op.add_column('topics', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_topics_brainstorm_id'), 'topics', ['brainstorm_id'], unique=False)
    op.create_index('ix_topics_brainstorm_proposition', 'topics', ['brainstorm_id', 'is_proposition'], unique=False)
    op.create_index(op.f('ix_topics_confidence'), 'topics', ['confidence'], unique=False)
    op.create_index(op.f('ix_topics_created_at'), 'topics', ['created_at'], unique=False)
    op.create_index(op.f('ix_topics_is_proposition'), 'topics', ['is_proposition'], unique=False)
    op.create_index(op.f('ix_topics_name'), 'topics', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topics_name'), table_name='topics')
    op.drop_index(op.f('ix_topics_is_proposition'), table_name='topics')
    op.drop_index(op.f('ix_topics_created_at'), table_name='topics')
    op.drop_index(op.f('ix_topics_confidence'), table_name='topics')
    op.drop_index('ix_topics_brainstorm_proposition', table_name='topics')
    op.drop_index(op.f('ix_topics_brainstorm_id'), table_name='topics')
    op.drop_column('topics', 'updated_at')
    op.drop_index(op.f('ix_topic_edges_target_topic_id'), table_name='topic_edges')
    op.drop_index(op.f('ix_topic_edges_source_topic_id'), table_name='topic_edges')
    op.drop_index('ix_topic_edges_source_target', table_name='topic_edges')
    op.drop_index(op.f('ix_topic_edges_relationship'), table_name='topic_edges')
    op.drop_index(op.f('ix_topic_edges_created_at'), table_name='topic_edges')
    op.drop_index('ix_topic_edges_brainstorm_rel', table_name='topic_edges')
    op.drop_index(op.f('ix_topic_edges_brainstorm_id'), table_name='topic_edges')
    op.drop_column('topic_edges', 'updated_at')
    op.drop_index(op.f('ix_messages_role'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_brainstorm_id'), table_name='messages')
    op.drop_index('ix_messages_brainstorm_created', table_name='messages')
    op.execute("ALTER TABLE messages ALTER COLUMN metadata_json TYPE TEXT USING metadata_json::text")
    op.drop_column('messages', 'updated_at')
    op.drop_index('ix_suggestion_dismissals_brainstorm', table_name='map_suggestion_dismissals')
    op.drop_index(op.f('ix_map_suggestion_dismissals_suggestion_name'), table_name='map_suggestion_dismissals')
    op.drop_index(op.f('ix_map_suggestion_dismissals_source_topic_id'), table_name='map_suggestion_dismissals')
    op.drop_index(op.f('ix_map_suggestion_dismissals_created_at'), table_name='map_suggestion_dismissals')
    op.drop_index(op.f('ix_map_suggestion_dismissals_brainstorm_id'), table_name='map_suggestion_dismissals')
    op.drop_index(op.f('ix_library_entries_topic_id'), table_name='library_entries')
    op.drop_index(op.f('ix_library_entries_folder_name'), table_name='library_entries')
    op.drop_index(op.f('ix_library_entries_created_at'), table_name='library_entries')
    op.drop_index(op.f('ix_library_entries_brainstorm_id'), table_name='library_entries')
    op.drop_index('ix_library_brainstorm_folder', table_name='library_entries')
    op.drop_index(op.f('ix_brainstorms_title'), table_name='brainstorms')
    op.drop_index('ix_brainstorms_deleted_at_created', table_name='brainstorms')
    op.drop_index(op.f('ix_brainstorms_deleted_at'), table_name='brainstorms')
    op.drop_index(op.f('ix_brainstorms_created_at'), table_name='brainstorms')
    op.drop_column('brainstorms', 'deleted_at')
    # ### end Alembic commands ###
