"""
initial

Revision ID: c982194ada87
Revises: 
Create Date: 2026-06-16 08:29:12.726307
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c982194ada87'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_settings_provider'), 'provider_settings', ['provider'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_email_tier', 'users', ['email', 'tier'], unique=False)
    op.create_index(op.f('ix_users_tier'), 'users', ['tier'], unique=False)
    op.create_table('brainstorms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('share_token', sa.UUID(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brainstorms_created_at'), 'brainstorms', ['created_at'], unique=False)
    op.create_index(op.f('ix_brainstorms_deleted_at'), 'brainstorms', ['deleted_at'], unique=False)
    op.create_index('ix_brainstorms_deleted_at_created', 'brainstorms', ['deleted_at', 'created_at'], unique=False)
    op.create_index(op.f('ix_brainstorms_share_token'), 'brainstorms', ['share_token'], unique=True)
    op.create_index(op.f('ix_brainstorms_title'), 'brainstorms', ['title'], unique=False)
    op.create_index(op.f('ix_brainstorms_user_id'), 'brainstorms', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brainstorm_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('parent_message_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['brainstorm_id'], ['brainstorms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_brainstorm_branch', 'messages', ['brainstorm_id', 'branch_id'], unique=False)
    op.create_index('ix_messages_brainstorm_created', 'messages', ['brainstorm_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_brainstorm_id'), 'messages', ['brainstorm_id'], unique=False)
    op.create_index(op.f('ix_messages_branch_id'), 'messages', ['branch_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_parent_message_id'), 'messages', ['parent_message_id'], unique=False)
    op.create_index(op.f('ix_messages_role'), 'messages', ['role'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brainstorm_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('library_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_proposition', sa.Boolean(), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['brainstorm_id'], ['brainstorms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_brainstorm_id'), 'topics', ['brainstorm_id'], unique=False)
    op.create_index('ix_topics_brainstorm_proposition', 'topics', ['brainstorm_id', 'is_proposition'], unique=False)
    op.create_index(op.f('ix_topics_confidence'), 'topics', ['confidence'], unique=False)
    op.create_index(op.f('ix_topics_created_at'), 'topics', ['created_at'], unique=False)
    op.create_index(op.f('ix_topics_is_proposition'), 'topics', ['is_proposition'], unique=False)
    op.create_index(op.f('ix_topics_name'), 'topics', ['name'], unique=False)
    op.create_table('library_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brainstorm_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('folder_name', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brainstorm_id'], ['brainstorms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_library_brainstorm_folder', 'library_entries', ['brainstorm_id', 'folder_name'], unique=False)
    op.create_index(op.f('ix_library_entries_brainstorm_id'), 'library_entries', ['brainstorm_id'], unique=False)
    op.create_index(op.f('ix_library_entries_created_at'), 'library_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_library_entries_folder_name'), 'library_entries', ['folder_name'], unique=False)
    op.create_index(op.f('ix_library_entries_topic_id'), 'library_entries', ['topic_id'], unique=False)
    op.create_table('map_suggestion_dismissals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brainstorm_id', sa.UUID(), nullable=False),
    sa.Column('source_topic_id', sa.UUID(), nullable=False),
    sa.Column('suggestion_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brainstorm_id'], ['brainstorms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brainstorm_id', 'source_topic_id', 'suggestion_name', name='uq_map_suggestion_dismissal')
    )
    op.create_index(op.f('ix_map_suggestion_dismissals_brainstorm_id'), 'map_suggestion_dismissals', ['brainstorm_id'], unique=False)
    op.create_index(op.f('ix_map_suggestion_dismissals_created_at'), 'map_suggestion_dismissals', ['created_at'], unique=False)
    op.create_index(op.f('ix_map_suggestion_dismissals_source_topic_id'), 'map_suggestion_dismissals', ['source_topic_id'], unique=False)
    op.create_index(op.f('ix_map_suggestion_dismissals_suggestion_name'), 'map_suggestion_dismissals', ['suggestion_name'], unique=False)
    op.create_index('ix_suggestion_dismissals_brainstorm', 'map_suggestion_dismissals', ['brainstorm_id', 'created_at'], unique=False)
    op.create_table('topic_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brainstorm_id', sa.UUID(), nullable=False),
    sa.Column('source_topic_id', sa.UUID(), nullable=False),
    sa.Column('target_topic_id', sa.UUID(), nullable=False),
    sa.Column('relationship', sa.String(length=255), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brainstorm_id'], ['brainstorms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_edges_brainstorm_id'), 'topic_edges', ['brainstorm_id'], unique=False)
    op.create_index('ix_topic_edges_brainstorm_rel', 'topic_edges', ['brainstorm_id', 'relationship'], unique=False)
    op.create_index(op.f('ix_topic_edges_created_at'), 'topic_edges', ['created_at'], unique=False)
    op.create_index(op.f('ix_topic_edges_relationship'), 'topic_edges', ['relationship'], unique=False)
    op.create_index('ix_topic_edges_source_target', 'topic_edges', ['source_topic_id', 'target_topic_id'], unique=False)
    op.create_index(op.f('ix_topic_edges_source_topic_id'), 'topic_edges', ['source_topic_id'], unique=False)
    op.create_index(op.f('ix_topic_edges_target_topic_id'), 'topic_edges', ['target_topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_edges_target_topic_id'), table_name='topic_edges')
    op.drop_index(op.f('ix_topic_edges_source_topic_id'), table_name='topic_edges')
    op.drop_index('ix_topic_edges_source_target', table_name='topic_edges')
    op.drop_index(op.f('ix_topic_edges_relationship'), table_name='topic_edges')
    op.drop_index(op.f('ix_topic_edges_created_at'), table_name='topic_edges')
    op.drop_index('ix_topic_edges_brainstorm_rel', table_name='topic_edges')
    op.drop_index(op.f('ix_topic_edges_brainstorm_id'), table_name='topic_edges')
    op.drop_table('topic_edges')
    op.drop_index('ix_suggestion_dismissals_brainstorm', table_name='map_suggestion_dismissals')
    op.drop_index(op.f('ix_map_suggestion_dismissals_suggestion_name'), table_name='map_suggestion_dismissals')
    op.drop_index(op.f('ix_map_suggestion_dismissals_source_topic_id'), table_name='map_suggestion_dismissals')
    op.drop_index(op.f('ix_map_suggestion_dismissals_created_at'), table_name='map_suggestion_dismissals')
    op.drop_index(op.f('ix_map_suggestion_dismissals_brainstorm_id'), table_name='map_suggestion_dismissals')
    op.drop_table('map_suggestion_dismissals')
    op.drop_index(op.f('ix_library_entries_topic_id'), table_name='library_entries')
    op.drop_index(op.f('ix_library_entries_folder_name'), table_name='library_entries')
    op.drop_index(op.f('ix_library_entries_created_at'), table_name='library_entries')
    op.drop_index(op.f('ix_library_entries_brainstorm_id'), table_name='library_entries')
    op.drop_index('ix_library_brainstorm_folder', table_name='library_entries')
    op.drop_table('library_entries')
    op.drop_index(op.f('ix_topics_name'), table_name='topics')
    op.drop_index(op.f('ix_topics_is_proposition'), table_name='topics')
    op.drop_index(op.f('ix_topics_created_at'), table_name='topics')
    op.drop_index(op.f('ix_topics_confidence'), table_name='topics')
    op.drop_index('ix_topics_brainstorm_proposition', table_name='topics')
    op.drop_index(op.f('ix_topics_brainstorm_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_messages_role'), table_name='messages')
    op.drop_index(op.f('ix_messages_parent_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_branch_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_brainstorm_id'), table_name='messages')
    op.drop_index('ix_messages_brainstorm_created', table_name='messages')
    op.drop_index('ix_messages_brainstorm_branch', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_brainstorms_user_id'), table_name='brainstorms')
    op.drop_index(op.f('ix_brainstorms_title'), table_name='brainstorms')
    op.drop_index(op.f('ix_brainstorms_share_token'), table_name='brainstorms')
    op.drop_index('ix_brainstorms_deleted_at_created', table_name='brainstorms')
    op.drop_index(op.f('ix_brainstorms_deleted_at'), table_name='brainstorms')
    op.drop_index(op.f('ix_brainstorms_created_at'), table_name='brainstorms')
    op.drop_table('brainstorms')
    op.drop_index(op.f('ix_users_tier'), table_name='users')
    op.drop_index('ix_users_email_tier', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_provider_settings_provider'), table_name='provider_settings')
    op.drop_table('provider_settings')
    # ### end Alembic commands ###
